### ISSUE TITLE
Flutter SDK

### ISSUE THREAD

**Issue by aloisdeniel** [adobe/react-native-acpcampaign#32]
Hi ! 

I noticed that several Flutter packages are available for the Adobe SDK, but this extension isn't yet. I haven't found any roadmap for it and my customer would like to integrate it into his app.

Do you have any short-term plans to release an SDK for Campaign which supports Flutter ?

Thank you.

**Comment by praschetan** [comment]
Hi @aloisdeniel - we don't have near-term plans to provide Flutter support for Campaign given current priorities. Recommend working with your Adobe CSM and account team if this is an important need for you.
